In [2]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
print(f" {x[0:1]} {type(x[0:1])} {x[0:1].shape}")
print(x[0])
y = x[0]
print(f" {y[0]} {type(y[0])} {y[0].shape}")


 [[1 2 3]] <class 'numpy.ndarray'> (1, 3)
[1 2 3]
 1 <class 'numpy.int64'> ()


In [3]:
x = np.zeros(3,)
x

array([0., 0., 0.])

In [4]:
import numpy as np

onehots = {}
onehots['cat'] = np.array([1,0,0,0])
onehots['the'] = np.array([0,1,0,0])
onehots['dog'] = np.array([0,0,1,0])
onehots['sat'] = np.array([0,0,0,1])
print(onehots)

sentence = ['the','cat','sat']
x = onehots[sentence[0]] + onehots[sentence[1]] + onehots[sentence[2]]

print("Sent Encoding:" + str(x))
x.shape


{'cat': array([1, 0, 0, 0]), 'the': array([0, 1, 0, 0]), 'dog': array([0, 0, 1, 0]), 'sat': array([0, 0, 0, 1])}
Sent Encoding:[1 1 0 1]


(4,)

In [22]:
import numpy as np
x = [[1,5], 
     [9,3]]
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[10  8]
[ 6 12]


In [35]:
x = np.ones([2,5])
y = np.ones([2,5])
x*y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
x = np.array([1,2,3])
a = x[np.array([0,1])]
a

array([1, 2])

In [40]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    ]

[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [61]:
import pandas as pd

x = np.array([10,2,3,40])
cols = ["first"]
df = pd.DataFrame(data=x, columns=cols)
#print(df.head())
x1 = list(map(lambda x: x>9, df["first"]))
(df["first"]>9).astype(float)

0    1.0
1    0.0
2    0.0
3    1.0
Name: first, dtype: float64

In [16]:
x = {'jog':[1,9,3,1,1,1,1], 'cat':[2,4], 'bat':[1,3]}
x

{'jog': [1, 9, 3, 1, 1, 1, 1], 'cat': [2, 4], 'bat': [1, 3]}

In [17]:
x['cat']

[2, 4]

In [18]:
y = {}

for item in x:
    y[item] = sum(x[item]) / len(x[item])

y

{'jog': 2.4285714285714284, 'cat': 3.0, 'bat': 2.0}

In [27]:
y.get

<function dict.get(key, default=None, /)>

In [29]:
key_max = max(y.keys(), key=(lambda k: y[k]))
key_max

'cat'

In [45]:
import numpy as np
x = np.array([[1,2],
              [0,9],
              [15,2]
             ])

print(x.shape)
print("no axis max", x.argmax())
print("axis=0", x.argmax(axis=1))

(3, 2)
no axis max 4
axis=0 [1 1 0]


In [61]:
x = {'cats': {'POSITIVE': True, 'NEGATIVE': False}}
int(x['cats']['NEGATIVE'] != True)

1

In [54]:
x['cats']

{'POSITIVE': True, 'NEGATIVE': True}

In [56]:
int(x['cats']['NEGATIVE'] != True)

0

In [72]:
x = np.array([2,2])
y = np.array([2,3])
x*y
x.

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'